apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: postgresql96
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: postgresql96
    spec:
      containers:
        - image: sqlfiddle:postgresql96Host
          imagePullPolicy: IfNotPresent
          name: postgresql96
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
              requests:
                memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - "/ready.sh"
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql96-service
  labels:
    role: host
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: database
  selector:
    type: postgresql96
